defaults: &defaults
  docker:
    - image: circleci/node:8.9.4

aliases:
  - &install-node-dependencies |
    npm install --no-package-lock --no-spin --no-progress

  - &filter-only-master
    branches:
      only:
        - master

  - &restore-node-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-dependencies-{{ checksum "package.json" }}

  - &save-node-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout

      - restore_cache: *restore-node-cache
      - run: *install-node-dependencies
      - save-cache: *save-node-cache

      - run: npm run lint

  danger:
    docker:
      - image: circleci/ruby:2.3

    working_directory: ~/repo

    steps:
      - checkout

      - run: gem install bundler
      - run: bundle install
      - run: git config user.name "CircleCI"
      - run: git config user.email "circleci@edtechfoundry.com"
      - run: bundle exec danger

  test:
    docker:
      - image: circleci/node:8.9.4
        environment:
          NODE_ENV: test
    steps:
      - checkout

      - restore_cache: *restore-node-cache
      - run: *install-node-dependencies
      - save-cache: *save-node-cache

      - run: npm run test

  build-and-push-image:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-push-image:
          filters: *filter-only-master
