defaults: &defaults
  docker:
    - image: circleci/node:8.9.4

aliases:
  - &install-node-dependencies
    |
      npm install --no-package-lock --no-spin --no-progress

  - &filter-only-master
    branches:
      only:
        - master

  - &restore-node-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-dependencies-{{ checksum "package.json" }}

  - &save-node-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

version: 2
jobs:

  lint:
    <<: *defaults
    steps:
      - checkout

      - restore_cache: *restore-node-cache
      - run: *install-node-dependencies
      - save-cache: *save-node-cache

      - run: npm run lint

  danger:
    docker:
      - image: circleci/ruby:2.3

    working_directory: ~/repo

    steps:
      - checkout

      - run: gem install bundler
      - run: bundle install
      - run: git config user.name "CircleCI"
      - run: git config user.email "circleci@edtechfoundry.com"
      - run: bundle exec danger

  test:
    docker:
      - image: circleci/node:8.9.4
        environment:
          NODE_ENV: test
    steps:
      - checkout

      - restore_cache: *restore-node-cache
      - run: *install-node-dependencies
      - save-cache: *save-node-cache

      - run: npm run test

  build-and-push-image:
    docker:
      - image: eu.gcr.io/differ-140008/circle-image:v1.1.1
        auth:
          username: _json_key
          password: $GCR_AUTH

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Decode Google Cloud Credentials
          command: echo $GCR_AUTH > ${HOME}/gcp-key.json
      - run: |
          gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

      - run:
          name: Authenticate Google Cloud Registry with Docker
          command: docker login -u _json_key -p "$(cat ${HOME}/gcp-key.json)" eu.gcr.io

      - run: |
          export VERSION="$(cat ./package.json | jq -r '.version')-${CIRCLE_BUILD_NUM}"
          export DOCKER_IMAGE=$(cat ./package.json | jq -r '.docker.imageUrl')

          export DOCKER_IMAGE_URL="${DOCKER_IMAGE}:${VERSION}"
          export DOCKER_IMAGE_LATEST_URL="${DOCKER_IMAGE}:latest"

          echo "Resolved version: ${VERSION}"

          ./build-service.sh

          docker push $DOCKER_IMAGE_URL
          docker push $DOCKER_IMAGE_LATEST_URL

          echo "Successfully pushed image: $DOCKER_IMAGE"

#      - run: cp /workspace/PUBLISHED_VERSION_NUMBER .

#      - persist_to_workspace:
#          root: .
#          paths:
#            - ./PUBLISHED_VERSION_NUMBER

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          context: org-global
      - danger:
          context: org-global
      - test:
          context: org-global
      - build-and-push-image:
          context: org-global
          filters: *filter-only-master
          requires:
            - lint
            - danger
            - test
